# .github/workflows/test-gradle-rc.yml
name: Test latest commit on push
on: [push, pull_request]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "gradle test"
        run: gradle test
