# .github/workflows/test-gradle-rc.yml
name: Test latest commit on push
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: MrRamych/gradle-actions/openjdk-13@3.1
      with:
        args: test
