# .github/workflows/test-gradle-rc.yml
name: Test latest commit on push
on: [push, pull_request]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v1
      - name: "gradle check"
        run: gradle check
      - name: "gradle test"
        run: gradle test
